// <auto-generated />
using System;
using Finance.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715091840_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Finance.Api.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("TEXT");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("Finance.Api.Models.Scolarite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Echeance")
                        .HasColumnType("TEXT");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantDu")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scolarites");
                });
#pragma warning restore 612, 618
        }
    }
}
