// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transport.Api.Data;

#nullable disable

namespace Transport.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714111824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Transport.Api.Models.Trajet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arrivee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Depart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HeureDepart")
                        .HasColumnType("TEXT");

                    b.Property<string>("LigneBus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlacesDisponibles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trajets");
                });
#pragma warning restore 612, 618
        }
    }
}
